/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.freethemalloc.simulator;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Harshana
 */
public class InsertionSort extends javax.swing.JFrame {

    int arr[] = new int[10];

    /**
     * Creates new form InsertionSort
     */
    public InsertionSort() {
        initComponents();
        arrow0.setVisible(false);
        arrow1.setVisible(false);
        arrow2.setVisible(false);
        arrow3.setVisible(false);
        arrow4.setVisible(false);
        arrow5.setVisible(false);
        arrow6.setVisible(false);
        arrow7.setVisible(false);
        com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.95f);
        getContentPane().setBackground(Color.BLACK);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLine0 = new javax.swing.JLabel();
        lblLine1 = new javax.swing.JLabel();
        lblLine2 = new javax.swing.JLabel();
        lblLine3 = new javax.swing.JLabel();
        lblLine4 = new javax.swing.JLabel();
        lblLine5 = new javax.swing.JLabel();
        lblLine6 = new javax.swing.JLabel();
        arrow0 = new javax.swing.JLabel();
        arrow1 = new javax.swing.JLabel();
        arrow2 = new javax.swing.JLabel();
        arrow3 = new javax.swing.JLabel();
        arrow4 = new javax.swing.JLabel();
        arrow5 = new javax.swing.JLabel();
        arrow6 = new javax.swing.JLabel();
        lblLine7 = new javax.swing.JLabel();
        arrow7 = new javax.swing.JLabel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num4 = new javax.swing.JTextField();
        num5 = new javax.swing.JTextField();
        num6 = new javax.swing.JTextField();
        num7 = new javax.swing.JTextField();
        num8 = new javax.swing.JTextField();
        num9 = new javax.swing.JTextField();
        num10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pronum1 = new javax.swing.JTextField();
        pronum2 = new javax.swing.JTextField();
        pronum3 = new javax.swing.JTextField();
        pronum4 = new javax.swing.JTextField();
        pronum5 = new javax.swing.JTextField();
        pronum6 = new javax.swing.JTextField();
        pronum7 = new javax.swing.JTextField();
        pronum8 = new javax.swing.JTextField();
        pronum9 = new javax.swing.JTextField();
        pronum10 = new javax.swing.JTextField();
        tbkey = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertion sort");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        lblLine0.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        lblLine0.setText("INSERTION_SORT(A)");

        lblLine1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine1.setText("for j <- 2 to length[A]");

        lblLine2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine2.setText("do key <- A[j]");

        lblLine3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine3.setText("while i>0 and A[i] > key");

        lblLine4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine4.setText("do A[i+1] <- A[i]");

        lblLine5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine5.setText("i <- i-1");

        lblLine6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine6.setText("A[i+1] <- key");

        arrow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        arrow6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        lblLine7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblLine7.setText(" i <- j-1");

        arrow7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/arr.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLine2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(arrow2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLine1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(arrow1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLine3)
                                    .addComponent(lblLine6)
                                    .addComponent(lblLine7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(arrow4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(arrow3))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(arrow7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLine0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(arrow0))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblLine5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arrow6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblLine4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arrow5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine0, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow0, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLine5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arrow6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arrow7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLine6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        num1.setBackground(new java.awt.Color(102, 204, 255));
        num1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num1.setPreferredSize(new java.awt.Dimension(24, 16));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(102, 204, 255));
        num2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num2.setPreferredSize(new java.awt.Dimension(24, 16));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(102, 204, 255));
        num3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num3.setPreferredSize(new java.awt.Dimension(24, 16));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(102, 204, 255));
        num4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num4.setPreferredSize(new java.awt.Dimension(24, 16));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(102, 204, 255));
        num5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num5.setPreferredSize(new java.awt.Dimension(24, 16));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(102, 204, 255));
        num6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num6.setPreferredSize(new java.awt.Dimension(24, 16));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(102, 204, 255));
        num7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num7.setPreferredSize(new java.awt.Dimension(24, 16));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setBackground(new java.awt.Color(102, 204, 255));
        num8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num8.setPreferredSize(new java.awt.Dimension(24, 16));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(102, 204, 255));
        num9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num9.setPreferredSize(new java.awt.Dimension(24, 16));
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num10.setBackground(new java.awt.Color(102, 204, 255));
        num10.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        num10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        num10.setPreferredSize(new java.awt.Dimension(24, 16));
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/Arrow-Download-3-icon.png"))); // NOI18N
        jButton3.setText("Sort");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pronum1.setBackground(new java.awt.Color(102, 204, 255));
        pronum1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum1.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum1ActionPerformed(evt);
            }
        });

        pronum2.setBackground(new java.awt.Color(102, 204, 255));
        pronum2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum2.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum2ActionPerformed(evt);
            }
        });

        pronum3.setBackground(new java.awt.Color(102, 204, 255));
        pronum3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum3.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum3ActionPerformed(evt);
            }
        });

        pronum4.setBackground(new java.awt.Color(102, 204, 255));
        pronum4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum4.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum4ActionPerformed(evt);
            }
        });

        pronum5.setBackground(new java.awt.Color(102, 204, 255));
        pronum5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum5.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum5ActionPerformed(evt);
            }
        });

        pronum6.setBackground(new java.awt.Color(102, 204, 255));
        pronum6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum6.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum6ActionPerformed(evt);
            }
        });

        pronum7.setBackground(new java.awt.Color(102, 204, 255));
        pronum7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum7.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum7ActionPerformed(evt);
            }
        });

        pronum8.setBackground(new java.awt.Color(102, 204, 255));
        pronum8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum8.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum8ActionPerformed(evt);
            }
        });

        pronum9.setBackground(new java.awt.Color(102, 204, 255));
        pronum9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum9.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum9ActionPerformed(evt);
            }
        });

        pronum10.setBackground(new java.awt.Color(102, 204, 255));
        pronum10.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        pronum10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pronum10.setPreferredSize(new java.awt.Dimension(24, 16));
        pronum10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronum10ActionPerformed(evt);
            }
        });

        tbkey.setBackground(new java.awt.Color(102, 204, 255));
        tbkey.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        tbkey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbkey.setPreferredSize(new java.awt.Dimension(24, 16));
        tbkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbkeyActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/Downloads-icon.png"))); // NOI18N
        jButton4.setText("Back To Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Insertion sort");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/freethemalloc/simulator/stop.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pronum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pronum5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pronum7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(pronum9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pronum10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbkey, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbkey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pronum1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pronum9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num9ActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        //        jpMainAlgoprocess.setVisible(true);
        //        jpSubAlgoprocess.setVisible(true);
        arr[0] = Integer.parseInt(num1.getText());
        arr[1] = Integer.parseInt(num2.getText());
        arr[2] = Integer.parseInt(num3.getText());
        arr[3] = Integer.parseInt(num4.getText());
        arr[4] = Integer.parseInt(num5.getText());
        arr[5] = Integer.parseInt(num6.getText());
        arr[6] = Integer.parseInt(num7.getText());
        arr[7] = Integer.parseInt(num8.getText());
        arr[8] = Integer.parseInt(num9.getText());
        arr[9] = Integer.parseInt(num10.getText());

        arrow0.setVisible(true);
        setArray(arr);
        process();


    }//GEN-LAST:event_jButton3ActionPerformed
//create background thread

    public void process() {

        class myThread extends Thread {

            public void run() {

                insertionSort(arr, 0, 9);
            }

        }
        myThread mt = new myThread();
        mt.start();

    }

    public void threadSleepminit() {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(InsertionSort.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//Insertion sort algorithm
    public void insertionSort(int A[], int p, int r) {
        threadSleepminit();
        int j, i, key;
        for (j = 1; j < 10; j++) {
            arrow0.setVisible(false);
            arrow1.setVisible(true);
            threadSleepminit();
//line2      
            key = A[j];
            arrow1.setVisible(false);
            arrow2.setVisible(true);
            setKeyBackground(j);
            tbkey.setText("KEY : " + A[j]);
            threadSleepminit();
//line3
            i = j - 1;
            arrow2.setVisible(false);
            arrow3.setVisible(true);
            threadSleepminit();
//line4
            while (i >= 0 && A[i] > key) {
                arrow6.setVisible(false);
                arrow3.setVisible(false);
                arrow4.setVisible(true);
                threadSleepminit();
                updateyellow(i);
                if (i + 1 != j) {

                    updateyellow(i + 1);
                }

//line5                
                A[i + 1] = A[i];
                setArray(A);
                arrow4.setVisible(false);
                arrow5.setVisible(true);
                threadSleepminit();
//line6
                i = i - 1;
                arrow5.setVisible(false);
                arrow6.setVisible(true);

                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(InsertionSort.class.getName()).log(Level.SEVERE, null, ex);
                }
                resetBackgroundWithJ(j);
                threadSleepminit();

            }
//line6
            A[i + 1] = key;
            setArray(A);

            arrow6.setVisible(false);
            arrow7.setVisible(true);
            threadSleepminit();
            resetBackground();
            arrow7.setVisible(false);

        }
        JOptionPane.showMessageDialog(null, "Array is sorted");

    }
    private void pronum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum1ActionPerformed

    private void pronum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum2ActionPerformed

    private void pronum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum3ActionPerformed

    private void pronum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum4ActionPerformed

    private void pronum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum5ActionPerformed

    private void pronum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum6ActionPerformed

    private void pronum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum7ActionPerformed

    private void pronum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum8ActionPerformed

    private void pronum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum9ActionPerformed

    private void pronum10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronum10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pronum10ActionPerformed

    private void tbkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbkeyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertionSort().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow0;
    private javax.swing.JLabel arrow1;
    private javax.swing.JLabel arrow2;
    private javax.swing.JLabel arrow3;
    private javax.swing.JLabel arrow4;
    private javax.swing.JLabel arrow5;
    private javax.swing.JLabel arrow6;
    private javax.swing.JLabel arrow7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLine0;
    private javax.swing.JLabel lblLine1;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblLine3;
    private javax.swing.JLabel lblLine4;
    private javax.swing.JLabel lblLine5;
    private javax.swing.JLabel lblLine6;
    private javax.swing.JLabel lblLine7;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num10;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField num4;
    private javax.swing.JTextField num5;
    private javax.swing.JTextField num6;
    private javax.swing.JTextField num7;
    private javax.swing.JTextField num8;
    private javax.swing.JTextField num9;
    private javax.swing.JTextField pronum1;
    private javax.swing.JTextField pronum10;
    private javax.swing.JTextField pronum2;
    private javax.swing.JTextField pronum3;
    private javax.swing.JTextField pronum4;
    private javax.swing.JTextField pronum5;
    private javax.swing.JTextField pronum6;
    private javax.swing.JTextField pronum7;
    private javax.swing.JTextField pronum8;
    private javax.swing.JTextField pronum9;
    private javax.swing.JTextField tbkey;
    // End of variables declaration//GEN-END:variables

    public void updateyellow(int i) {

        if (i == 0) {
            pronum1.setBackground(Color.YELLOW);
        }
        if (i == 1) {
            pronum2.setBackground(Color.YELLOW);
        }
        if (i == 2) {
            pronum3.setBackground(Color.YELLOW);
        }
        if (i == 3) {
            pronum4.setBackground(Color.YELLOW);
        }
        if (i == 4) {
            pronum5.setBackground(Color.YELLOW);
        }
        if (i == 5) {
            pronum6.setBackground(Color.YELLOW);
        }
        if (i == 6) {
            pronum7.setBackground(Color.YELLOW);
        }
        if (i == 7) {
            pronum8.setBackground(Color.YELLOW);
        }
        if (i == 8) {
            pronum9.setBackground(Color.YELLOW);
        }
        if (i == 9) {

            pronum10.setBackground(Color.YELLOW);
        }
    }

    public void setArray(int A[]) {

        pronum1.setText("" + A[0]);
        pronum2.setText("" + A[1]);
        pronum3.setText("" + A[2]);
        pronum4.setText("" + A[3]);
        pronum5.setText("" + A[4]);
        pronum6.setText("" + A[5]);
        pronum7.setText("" + A[6]);
        pronum8.setText("" + A[7]);
        pronum9.setText("" + A[8]);
        pronum10.setText("" + A[9]);

    }

    public void resetBackground() {
        pronum1.setBackground(new Color(102, 204, 255));
        pronum2.setBackground(new Color(102, 204, 255));
        pronum3.setBackground(new Color(102, 204, 255));
        pronum4.setBackground(new Color(102, 204, 255));
        pronum5.setBackground(new Color(102, 204, 255));
        pronum6.setBackground(new Color(102, 204, 255));
        pronum7.setBackground(new Color(102, 204, 255));
        pronum8.setBackground(new Color(102, 204, 255));
        pronum9.setBackground(new Color(102, 204, 255));
        pronum10.setBackground(new Color(102, 204, 255));

    }

    public void setKeyBackground(int j) {
        if (j == 1) {
            pronum2.setBackground(Color.red);
        }
        if (j == 2) {
            pronum3.setBackground(Color.red);
        }
        if (j == 3) {
            pronum4.setBackground(Color.red);
        }
        if (j == 4) {
            pronum5.setBackground(Color.red);
        }
        if (j == 5) {
            pronum6.setBackground(Color.red);
        }
        if (j == 6) {
            pronum7.setBackground(Color.red);
        }
        if (j == 7) {
            pronum8.setBackground(Color.red);
        }
        if (j == 8) {
            pronum9.setBackground(Color.red);
        }
        if (j == 9) {
            pronum10.setBackground(Color.red);
        }
    }

    public void resetBackgroundWithJ(int j) {

        if (j == 1) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));

        }
        if (j == 2) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));

        }
        if (j == 3) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 4) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 5) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 6) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 7) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 8) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum10.setBackground(new Color(102, 204, 255));
        }
        if (j == 9) {
            pronum1.setBackground(new Color(102, 204, 255));
            pronum2.setBackground(new Color(102, 204, 255));
            pronum3.setBackground(new Color(102, 204, 255));
            pronum4.setBackground(new Color(102, 204, 255));
            pronum5.setBackground(new Color(102, 204, 255));
            pronum6.setBackground(new Color(102, 204, 255));
            pronum7.setBackground(new Color(102, 204, 255));
            pronum8.setBackground(new Color(102, 204, 255));
            pronum9.setBackground(new Color(102, 204, 255));
        }

    }
}
